apiVersion: azureextraupjet.idp.microserfin.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: azure-secret
      namespace: crossplane-system
      key: creds
